import turtle

def draw():

    pen = turtle.Turtle()
    pen.pensize('10')
    pen.speed('fastest')
    pen.hideturtle()

#initial square draw
    pen.penup()
    pen.goto(300, 300)
    pen.pendown()
    pen.setheading(270)
    pen.fd(600)
    pen.right(90)
    pen.fd(600)
    pen.right(90)
    pen.fd(600)
    pen.right(90)
    pen.fd(525)
    pen.penup()

#horizontal lines

    pen.goto(300, 225)
    pen.setheading(180)
    pen.pendown()
    pen.fd(225)
    pen.penup()
    pen.fd(75)
    pen.pendown()
    pen.fd(225)
    pen.penup()

    pen.goto(300, 150)
    pen.pendown()
    pen.fd(75)
    pen.penup()
    pen.fd(150)
    pen.pendown()
    pen.fd(75)
    pen.penup()
    pen.fd(150)
    pen.pendown()
    pen.fd(150)
    pen.penup()

    pen.goto (225, 75)
    pen.pendown()
    pen.fd(150)
    pen.penup()
    pen.fd(75)
    pen.pendown()
    pen.fd(225)
    pen.penup()

    pen.goto(150, -75)
    pen.pendown()
    pen.fd(150)
    pen.penup()
    pen.fd(150)
    pen.pendown()
    pen.fd(150)
    pen.penup()

    pen.goto(225, -150)
    pen.pendown()
    pen.fd(75)
    pen.penup()
    pen.fd(75)
    pen.pendown()
    pen.fd(150)
    pen.penup()
    pen.fd(75)
    pen.pendown()
    pen.fd(75)
    pen.penup()

    pen.goto(0, -225)
    pen.pendown()
    pen.fd(150)
    pen.penup()

#vertical lines

    pen.goto(-225, -300)
    pen.setheading(90)
    pen.pendown()
    pen.fd(150)
    pen.penup()
    pen.fd(150)
    pen.pendown()
    pen.fd(75)
    pen.penup()

    pen.goto(-150, -75)
    pen.pendown()
    pen.fd(75)
    pen.penup()

    pen.goto(-75, -225)
    pen.pendown()
    pen.fd(225)
    pen.penup()
    pen.fd(75)
    pen.pendown()
    pen.fd(150)
    pen.penup()

    pen.goto(0, -75)
    pen.pendown()
    pen.fd(150)
    pen.penup()
    pen.fd(150)
    pen.pendown()
    pen.fd(75)
    pen.penup()

    pen.goto(75, -225)
    pen.pendown()
    pen.fd(150)
    pen.penup()
    pen.fd(75)
    pen.pendown()
    pen.fd(75)
    pen.penup()
    pen.fd(75)
    pen.pendown()
    pen.fd(75)
    pen.penup()

    pen.goto(150, -300)
    pen.pendown()
    pen.fd(150)
    pen.penup()
    pen.fd(75)
    pen.pendown()
    pen.fd(75)
    pen.penup()
    pen.fd(75)
    pen.pendown()
    pen.fd(150)
    pen.penup()

    pen.goto(225, -225)
    pen.pendown()
    pen.fd(75)
    pen.penup()
    pen.fd(75)
    pen.pendown()
    pen.fd(150)
    pen.penup()
